INSERT INTO bingo_fact (fact_text) VALUES
  ('Ju wechselt plötzlich das Thema'),
  ('Rezo sagt ''Spaaaaaaß'''),
  ('Rezo lobt sich selbst'),
  ('Ju lobt sich selbst'),
  ('Ju sagt ''Spaaaaaaß'''),
  ('Ju stöhnt etwas, oder betont es unnötig sexual'),
  ('Ju erwähnt Vagina / Vulva'),
  ('Rezo erwähnt Vagina / Vulva'),
  ('Ju erwähnt Penis'),
  ('Rezo erwähnt Penis'),
  ('Rezo macht keinen Mathe-Fact'),
  ('5-Sterne Bewertung wird erwähnt'),
  ('Rezo antwortet mit ''Hää?'''),
  ('Ju sagt was dummes, kurze Pause, beide lachen'),
  ('Ju sagt ''Ach, Freunde!'''),
  ('Einer der beiden erwähnt das es sich um einen News Podcast handelt'),
  ('Rezo erinnert Ju daran nicht zu viel zu versprechen'),
  ('Rezo spricht ein ''t'' wie ein ''d'' aus'),
  ('Rezo sagt ''Weiiiiß ich jetzt nicht'''),
  ('Ju wird auf Tinder angesprochen'),
  ('Geschlechtsverkehr wird erwähnt'),
  ('Ein neues Intro wird erstellt / soll erstellt werden'),
  ('Rezo versucht Ju einen Fuß-fetisch unter zu jubeln'),
  ('Ju versucht Rezo einen Muttermilch-fetisch unter zu jubeln'),
  ('Einer der beiden hat Angst vor Marina'),
  ('Rezo erklärt einen Mathe-Fact'),
  ('Eine Städtegeschichte wird erzählt'),
  ('"Medium ugly" wird gesagt'),
  ('"Lobbyhoe(s)" wird erwähnt'),
  ('"Wallen" oder "Walls" wird gesagt'),
  ('"Lobbyfoe" wird erwähnt'),
  ('Ju erzählt eine Tinder-Geschichte'),
  ('Einer unterbricht den anderen'),
  ('Beide lachen gleichzeitig laut auf'),
  ('Einer sagt "Digga"'),
  ('Einer sagt "Sorry"'),
  ('Ju erwähnt seinen Vater'),
  ('Rezo erwähnt Spotify oder eine Playlist'),
  ('Männlichkeit wird thematisiert'),
  ('Einer vergleicht etwas mit einem Tier'),
  ('Eine Hörernachricht / Community-Story wird vorgelesen'),
  ('Rezo macht einen Wortspiel / Pun'),
  ('Ju sagt etwas Falsches und Rezo korrigiert ihn'),
  ('"Krasser Ficker" wird gesagt'),
  ('Ju erwähnt Muttermilch'),
  ('Einer reagiert mit "O_o" / ist sprachlos'),
  ('Religion oder Gott wird erwähnt'),
  ('Rezo erwähnt YouTube oder die YouTube-Karriere'),
  ('Einer sagt "safe"'),
  ('Ju oder Rezo vergleicht etwas mit Essen / Kochen');
